---
title: "Bike Peddler"
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
```

```{r, warning=FALSE, message=FALSE}
source("process_data.R")
base_columns <- names(store)[!names(store) %in% c("Year", "Month")]
```

```{r}
GGally::ggpairs(store, columns = base_columns)
```

```{r, message=FALSE, warning=FALSE}
GGally::ggpairs(store, columns = c(base_columns, "Year"),
                mapping = ggplot2::aes(color = Year))
```

```{r, message=FALSE, warning=FALSE}
GGally::ggpairs(category, columns = base_columns,
                mapping = ggplot2::aes(color = Category))
```

```{r, message=FALSE, warning=FALSE}
p <- GGally::ggpairs(type, columns = base_columns,
                     mapping = ggplot2::aes(color = Type)) 
plotly::ggplotly(p)
```







```{r}
lm_fit <- lm(Revenue ~ Category + Type + Qty_Sold, data = type)
summary(lm_fit)

```

```{r}
type %>%
  dplyr::group_by(Category, Type) %>%
  dplyr::summarize(min = min(Qty_Sold), median = median(Qty_Sold), 
                   max = max(Qty_Sold))
```


```{r, warning=FALSE}
boot_type <- type %>%
  dplyr::select(Category, Type, Qty_Sold) %>%
  sample_n(10000, replace = TRUE)
boot_type$Revenue <- predict(lm_fit, boot_type)


```

```{r}

input_data_frame <- read.table(header = TRUE, stringsAsFactors = FALSE, text = '
Category Type input
Acessories	Clothes	60
Acessories	Helmets	70
Acessories	Parts 200
Bikes	Hybrid 20
Bikes	Kids 11
Bikes	Mountain 10	
Bikes	Road 11
')

get_revenue_prediction <- function(dat, input_data_frame) {
  # dat <- boot_type
  
  percentiles <- dat %>%
    dplyr::group_by(Category, Type) %>%
    dplyr::mutate(percentile = ntile(Qty_Sold, 10)) %>%
    dplyr::group_by(Category, Type, percentile) %>%
    dplyr::mutate(min = min(Qty_Sold), max = max(Qty_Sold)) %>%
    dplyr::left_join(input_data_frame, c("Category", "Type")) %>%
    dplyr::filter(max >= input & min < input) %>%
    dplyr::ungroup()

  percentiles
}
```

```{r}
pred <- get_revenue_prediction(boot_type, input_data_frame) %>%
  dplyr::select(Category, Type, Revenue) %>%
  dplyr::mutate(Data = "Selected")

plot_data <- boot_type %>%
  dplyr::select(Category, Type, Revenue) %>%
  dplyr::mutate(Data = "All")

plot_data <- rbind(pred, plot_data)

p <- ggplot(plot_data, aes(Data, Revenue)) + geom_boxplot()
print(p)
```